ALTER TABLE "Profile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Module" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModuleDetail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ComponentItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attachment" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "module_assets_public_read" ON storage.objects;
